### ISSUE TITLE
Refactor name matching into a class

### ISSUE THREAD

**Issue by dills122** [dills122/MTG-Card-Analyzer#18]
To keep the code standardized across the repo, `match-name.js` should be refactored into a class.

[match-name.js](https://github.com/dills122/mtg-card-analyzer/blob/ed0188f40d9893884ffc884cfccd1826a4c5306a/src/fuzzy-matching/match-name.js)

[reference class](https://github.com/dills122/mtg-card-analyzer/blob/042ae871556bc6563bbd1c3da6f7707a14656ad8/src/processor/processor.js)

**Comment by jpcasey** [comment]
I just submitted PR #24 for this and tried to follow the style in the reference class.  Is this along the lines of what you were looking for?
